# Exam Agenda - Q4: Projections and Least Squares

## Focus on the relation between linear least squares (function minimization) and projections.
- `05-projection-tutorial`
    - Projection on a line, where A is a column vector
        - Projection matrix: $P = A(A^{\top}A)^{-1}A^{\top}$
        - Projected points, ($\hat{y}$ is the projected points and y is the actual points): $\hat{y} = Py$
    - Linear least square: 
        - Find a line that minimises the error
        - $y = \mathbf{w}_1x + \mathbf{w}_0$
        - With mulitple points: 
        - $\begin{array}{cccc}
            y &= & A &w \\
            \begin{bmatrix}y_1 \\ \vdots \\ y_n \end{bmatrix} 
                &=
                &\begin{bmatrix}x_1 & 1 \\ \vdots & \vdots \\ x_n & 1\end{bmatrix} 
                &w
            \end{array}$
        - Since the projected points $\hat{y}$ is in the span of A (see figure 2), then: $\hat{y}=Aw$ (linear combination)
        - Thus: $A\mathbf{w} = P \mathbf{y}=A(A^\top A)^{-1}A^\top \mathbf{y}$
        - By dividing A on both sides: $w = (A^{\top}A)^{-1}A^{\top}y$
- Measure error once line is found
    - RMS is used to calculate the error
    - The further away from the line, the larger error
    - When the linear equation is perfectly determined, RMS = 0
    - We use least square when $n > m$
    - Outliers on a fitted line

## Focus on linear least squares problems for model fitting (design matrix, kernel, lines, polynomials, affine, and other multivariate functions) and the interpretation of results for various types of models (see week 7).
- What is linear least squares
    - Fits a line while minimising error
    - More knowns than unknowns
- Focus: Task 3 in [02-model-complexity](../w7/02-model_complexity.ipynb) week 7 (predicting growth of trees)
    - Least square for different polynomials
        - Design matrix for different polynomials
            - As manny degrees of polynomials as the model (+ 1)
            - 2 degree polynomial: $A = \begin{bmatrix}x_1^2 & x_1 & 1\\\vdots & \vdots & \vdots\\x_n^2 & x_n&1\end{bmatrix}$
        - Task 3 shows least squares for different polynimals
            - 6 is overfit, does good on training but very bad on test data
            - 1 is doing good on both training and test data
        - Goal: find a model that performs well on training and test data

## Learning of Affine (multivariate) functions and linear optimization.
- What is an affine function
    - Depends on multiple input parameters (both x and y)
- Focus: [w5/02-affine_spatial_regression.ipynb](../w5/02-affine_spatial_regression.ipynb)
    - Mapping coordinates from 3D atrium to 2D atrium
    - This is multivariete function
    - Affine since $w_3$ and $w_6$ is bias terms
    - Task 1 to explain how T and A, w, b relates
    - Task 5 reflects on how accuracy can be improved 
        - Least squares if we have more than 3 points



# Experimenting with the tutorial
The following tasks are related to the week 4 tutorial.
 
The individual tasks will ask you to either reflect on parts of the tutorial or modify specific code cells from the tutorial. Specifically, [Task 2](#project) and [Task 3](#ls) require modifications to the code of your copy of the tutorial notebook.
 

<article class="message">
    <div class="message-body">
        <strong>List of tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#copy">Task 1: Copy notebook</a>
            </li>
            <li>
            <a href="#project">Task 2: Projection experiments</a>
            </li>
            <li>
            <a href="#ls">Task 3: Linear Least Squares Experiments</a>
            </li>
            <li>
            <a href="#poly">Task 4: Second-order polynomial</a>
            </li>
            <li>
            <a href="#pmatrix">Task 5: Projection matrix</a>
            </li>
        </ul>
    </div>
</article>

## Experiments for the tutorial notebook
<article class="message task"><a class="anchor" id="copy"></a>
    <div class="message-header">
        <span>Task 1: Copy notebook</span>
        <span class="has-text-right">
          <i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Copy the tutorial notebook
 in the repository. 
This makes it easy to go back to the original in case something goes wrong.


</div></article>

<article class="message task"><a class="anchor" id="project"></a>
    <div class="message-header">
        <span>Task 2: Projection experiments</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


This task builds on the $\textbf{Projections}$ section in the tutorial.
1. Search and identify comment `##1`
. 
2. Change the values of the matrix $A$ (below comment `##1`
) to modify the line. Experiment with different values and observe how the projection changes in the plot.
3. Change the matrix $A$, such that $PX$ ≈ $X$ (that is the projection leaves $X$ almost unchanged). 
4. Search and identify comment `##2`
.
5. Set the matrix $A$  = $\begin{bmatrix} 1 \\ 0.5 \end{bmatrix}$, then apply the projection matrix $P$ twice, i.e. calculate $PPX$ (just below the comment). How does this affect the projected points?



</div></article>



In [1]:
# Write your solution here

# PX nearly equals X when A = 1,1. The values are
# projected points:
#  [[1.  2.  2.5]
#  [1.  2.  2.5]]
# original points:
#  [[1 2 3]
#  [1 2 2]]


# When applying P twice (x_prime = P @ P @ X) the result is
# exactly the same as when doing it only once (x_prime = P @ X)



<article class="message task"><a class="anchor" id="ls"></a>
    <div class="message-header">
        <span>Task 3: Linear Least Squares Experiments</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


This task builds on the $\textbf{Linear Least Squares}$ section in the tutorial.
1. Search and identify comment `##3`
.
2. Change the values of the first point in the matrix `X`
 such that it gradually moves further and further away from the line. Observe how it affects the error $RMS$.
3. Add two points to `X`
 and observe how they affect the fitted line and the error.    - How can you change the two additional points so the fitted line does not move?


4. What happens to the error when removing all but two points from `X`
?
5. What happens when you remove all but one point from `X`
?
6. Reflect on how the quality of the data affects the projection and thus the solution. 



</div></article>



In [2]:
# Write your solution here
# 2. As the first point moves further away from the line of two other points the rms increases.

# 3. If I add two points 4,4 and 5,5 the line changes, but when I then change the two points to 6,6 and 7,7, the line does not change. If the two new points have the same distance (error) to the line as the two previos ones, then the line does not change.

# 4. If you remove all but two points then the line fits perfectly and the rms is 0.

# 5. If you remove all but one point, it will fail as it needs at least as many points as unknown (slope and intersection, a and b), so in this case two points.

# 6. Outliers can affect the projection a lot.
# An example is if you have one outlier (0,6), it will affect the line a lot. There is a trend of all the other points, but this one point that is off changes the line from following the trend.
# X = np.array([
#     [1, 1],
#     [2, 2],
#     [3, 2],
#     [5,5],
#     [6,6],
#     [0,6]
# ]).T


## Pen and paper exercises
A 2. order polynomial is given by 

$$f(x) = w_0 + w_1x + w_2x^2 = \sum^2_{i=0} w_ix^i.$$

Generally, an $N$'th order  polynomial is given by

$$f(x) = \sum^N_{i=0} w_ix^i,$$
where $\mathbb{w}$ is a vector of coefficients.
<article class="message task"><a class="anchor" id="poly"></a>
    <div class="message-header">
        <span>Task 4: Second-order polynomial</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


1. Identify the knowns and unknowns in the polynomial above.
2. Is the function linear or non-linear in $\mathbb{w}$?
3. Is the function linear or non-linear in $\mathbb{x}$?
4. Provide the outline of an algorithm for fitting a second-order polynomial using linear least squares.
5. Generalize this algorithm to n-th order polynomials.



</div></article>



In [3]:
# Write your solution here
# 1. x and f(x) are knowns and w are unknowns
# 2. and 3. It is linear in w and non-linear in x
# 4. Add the x coordinates of the points to A such that the first row in A has 1's. the second has x and the third has x^2.
# A = np.array([
#     [1, x1, x1^2],
#     [1, x2, x2^2],
#     [1, x3, x3^2],
#      ....
# ])
# Add all the y coordinates to a vector b
# b = np.array([
#     [y1],
#     [y2],
#     [y3],
#      ...
# ])

# use linear least squares to find the vector w.(see the formula below)

# 5. Do the exact same as described above, but change A so it has all the polynomials of x.


$$
\mathbf{w} = (A^\top A)^{-1}A^\top \mathbf{y}.
$$

<article class="message task"><a class="anchor" id="pmatrix"></a>
    <div class="message-header">
        <span>Task 5: Projection matrix</span>
        <span class="has-text-right">
          <i class="bi bi-infinity"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


The projection matrix $P = A(A^\top A )^{-1}A^\top$ is, under certain conditions, equal to the identity matrix.
1. Give an example of a design matrix $A$ for which $P=I$.
2. Explain why projection matrices are usually not identity matrices.
3. (optional) Prove a condition for which $P=I$. Hint: when is $A^\top A=I$?.



</div></article>



In [4]:
# Write your solution here