# Plan for Q2 Exercises Week 3 (Matrices)

### a) Focus on matrices and their operations (addition, multiplication, transpose, inverse, determinant, orthogonal). Relate them to their applications within the course (e.g. transformations, basis in week 11)
- Matrices
    - A matrix is a set of elements ordered by row and column
    - Square matrix: A matrix that has same number of rows and columns
    - Identity matrix: diagonal 1’s, the rest is 0
    - Diagonal: there is only numbers diagonally, the rest is 0
- Matrix operations
    - Addition and subtraction (Task 1)
    - Scalar multiplication
    - Transpose (Task 7)
    - Orthogonal matrix
        - $A^\intercal = A^{-1}\\ or \\ AA^\intercal = A^\intercal A=I$
    - Inverse (Task 4)
        - $A^{-1}A = AA^{-1}=I$
        - To calculate it by hand for a 2x2 matrix
            - $\begin{bmatrix} a & b  \\ c & d \\ \end{bmatrix}^{-1} = \dfrac{1}{ad-bc} \begin{bmatrix} d & -b  \\ -c & a \\ \end{bmatrix}$
        - Properties of inverse (Task 5)
            - $D^{-1}E^{-1} = (ED)^{-1} \\ D^{-1}E^{-1} \neq (DE)^{-1}$
        - Pseudoinverse
            - $pseudo\_inverse= (A^{\top}A)^{-1}A^{\top}$
    - Determinants: (Task 6) 
        - The determinant of a matrix is used to figure out if a matrix has an inverse. If a matrix determinant is 0 then there is no inverse because it has either 0 or infinite solutions
        - $det(\begin{bmatrix} a & b  \\ c & d \\ \end{bmatrix}) = ad-bc$
    - Matrix multiplication (Task 2 and 9)
        - number of columns in matrix a = number of rows in matrix b
        - 
        $\begin{bmatrix}
            a_1 & a_2 & a_3 \\
            a_4 & a_5 & a_6 \\
            a_7 & a_8 & a_9 \\
            \end{bmatrix}
            \cdot
            \begin{bmatrix}
            b_1 & b_2 \\
            b_3 & b_4 \\
            b_5 & b_6 \\
            \end{bmatrix}
            =
            \begin{bmatrix}
            a_1b_1 + a_2b_3 + a_3b_5 & a_1b_2 + a_2b_4 + a_3b_6 \\
            a_4b_1 + a_5b_3 + a_6b_5 & a_4b_2 + a_5b_4 + a_6b_6 \\
            a_7b_1 + a_8b_3 + a_9b_5 & a_7b_2 + a_8b_4 + a_9b_6 \\
            \end{bmatrix}$
    - Transformations
        - basis vectors as matrix
        $$\begin{bmatrix}
            1 & 0 \\
            0 & 1 \\
            \end{bmatrix}$$
        - transposed basis vector
        $$\begin{bmatrix}
            0 & -1 \\
            1 & 0 \\
            \end{bmatrix}$$


### b) Focus on how linear equations and their solutions are related to matrices

- Inner products and polynomials as inner products
- Matrix multiplication
- Solving linear equations (Task 8)
    - focus on task 8a
        - Set up equation as matrices and vectors
             $$Az=b
                \\A=
                \begin{bmatrix}
                2 & 3 \\
                1 & 1 \\
                \end{bmatrix}
                \\
                b=
                \begin{bmatrix}
                -1 \\
                0\\
                \end{bmatrix}
                \\
                z=\begin{bmatrix}
                x  \\
                y  \\
                \end{bmatrix}$$
        - Determinant 
            - $det(\begin{bmatrix} a & b  \\ c & d \\ \end{bmatrix}) = ad-bc$
            - $det(\begin{bmatrix} 2 & 3  \\ 1 & 1 \\ \end{bmatrix}) = 2*1-3*1=-1$
        - Inverse
            - $A^{-1}A = AA^{-1}=I$
            $$\begin{bmatrix}
                a & b  \\
                c & d \\
                \end{bmatrix}^{-1} = \dfrac{1}{ad-bc} \begin{bmatrix}
                d & -b  \\
                -c & a \\
                \end{bmatrix}\\
                \begin{bmatrix}
                2 & 3  \\
                1 & 1 \\
                \end{bmatrix}^{-1} = \dfrac{1}{2*1-3*1} \begin{bmatrix}
                1 & -3  \\
                -1 & 2 \\
                \end{bmatrix}
                =-1\begin{bmatrix}
                1 & -3  \\
                -1 & 2 \\
                \end{bmatrix}
                =\begin{bmatrix}
                -1 & 3  \\
                1 & -2 \\
                \end{bmatrix}$$
            - solve for z
                $$
                z=A^{-1}b=\begin{bmatrix}
                -1 & 3  \\
                1 & -2 \\
                \end{bmatrix}
                ·
                \begin{bmatrix}
                -1  \\
                0 \\
                \end{bmatrix}=
                \begin{bmatrix}
                -1*-1+0*3  \\
                -1*1+0*-2 \\
                \end{bmatrix}=\begin{bmatrix}
                1  \\
                -1 \\
                \end{bmatrix}$$
                - This means that x=1 and y=-1 for the two equations.
            - Pseudoinverse if matrix is not n*n
                - $pseudo\_inverse= (A^{\top}A)^{-1}A^{\top}$


# Linear Algebra
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 10: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

## Matrix Operations
<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [4]:
# Write your solution here
a_sub_b = np.subtract(A, B)
# a_sub_b = A - B
print("A")
print(A)
print("B")
print(B)
print("A - B")
print(a_sub_b)

A
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
B
[[-16  15 -14  13]
 [-12  11 -10   9]
 [ -8   7  -6   5]
 [ -4   3  -2   1]]
A - B
[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.



</div></article>



In [11]:
# Write your solution here
ac = A @ C
ca = C @ A
print(ac)
print(ca)
# Because matrix multiplication mutiply a row by a column so the order makes a difference (row vs col)

[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication - Hadamard product</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.



</div></article>



In [9]:
# Write your solution here
a_ele_c = A * C
print(a_ele_c)
a_mul_c = A @ C
print(a_mul_c)
# * is element wise multiplication and @ is matrix multiplication

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]
[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]


<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 4: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [31]:
# Write your solution here
a_inv = np.linalg.inv(A)
c_inv = np.linalg.inv(C)
# print(a_inv)
# print(c_inv)
identity = np.identity(4)
a_indentity = a_inv @ A
c_indentity = c_inv @ C
print(f"{a_indentity} equals \n{identity}")
print(f"{c_indentity} equals \n{identity}")
# The result is very close to being the identity but because we use floating points the accuracy is not a 100% correct
print(f"with round: \n{np.round(a_indentity)} equals \n{identity}")
print(f"{np.round(c_indentity)} equals \n{identity}")

[[ 1.00000000e+00 -5.81756865e-15  1.11022302e-16 -3.45755171e-15]
 [ 2.27373675e-13  1.00000000e+00  6.02481028e-14  9.63039172e-14]
 [-2.27373675e-13 -1.60316205e-13  1.00000000e+00 -1.61585031e-13]
 [ 0.00000000e+00  5.38236122e-14  3.09382150e-14  1.00000000e+00]] equals 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.00000000e+00 -1.07802656e-13 -7.46069873e-14 -5.51287411e-14]
 [ 1.42108547e-13  1.00000000e+00  1.42108547e-14  3.23074900e-14]
 [-1.70530257e-13  2.37746331e-13  1.00000000e+00  3.14390489e-13]
 [ 5.68434189e-14 -2.66104599e-13 -2.55795385e-13  1.00000000e+00]] equals 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
with round: 
[[ 1. -0.  0. -0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]
 [ 0.  0.  0.  1.]] equals 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1. -0. -0. -0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0. -0. -0.  1.]] equals 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 5: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [18]:
# Write your solution here
d_inv = np.linalg.inv(D)
e_inv = np.linalg.inv(E)
ed_inv = np.linalg.inv((E @ D))
de_inv = np.linalg.inv((D @ E))

print("d_inv @ e_inv equals (e @ d)_inv ")
print(f"{(d_inv @ e_inv)} = \n{ed_inv}")

print("\nd_inv @ e_inv does not equals (d @ e)_inv ")
print(f"{(d_inv @ e_inv)} != \n{de_inv}")


d_inv @ e_inv equals (e @ d)_inv 
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]] = 
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]

d_inv @ e_inv does not equals (d @ e)_inv 
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]] != 
[[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 6: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [44]:
# Write your solution here
a_det = np.linalg.det(A)
b_det = np.linalg.det(B)
c_det = np.linalg.det(C)
print(f"a_det: {a_det}")
print(f"b_det: {b_det}")
print(f"c_det: {c_det}")
# b_det is very close to 0 so i assume that b does not have an inverse, but a and c does
a_inv = np.linalg.inv(A)
b_inv = np.linalg.inv(B)
c_inv = np.linalg.inv(C)
print(f"a_inv: {a_inv}")
print(f"b_inv: {b_inv}")
print(f"c_inv: {c_inv}")
# b's inverse has very high numbers compared to the two others, so I think it is trying to calculate something
# that is cannot, meaning that b doesn't have an inverse

a_det: 12.000000000000005
b_det: 2.7733391199176e-32
c_det: 1.0498026371041163e-07
a_inv: [[-1.00000000e+00 -5.55111512e-17  5.00000000e-01]
 [ 5.00000000e-01 -5.00000000e-01  1.58603289e-17]
 [ 1.16666667e+00 -5.00000000e-01 -1.66666667e-01]]
b_inv: [[-3.00239975e+16  4.80383960e+16 -6.00479950e+15 -1.20095990e+16]
 [-4.80383960e+16  7.20575940e+16 -0.00000000e+00 -2.40191980e+16]
 [-6.00479950e+15  0.00000000e+00  1.80143985e+16 -1.20095990e+16]
 [ 1.20095990e+16 -2.40191980e+16  1.20095990e+16 -0.00000000e+00]]
c_inv: [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]


<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 7: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [26]:
# Write your solution here
# D = np.array([
#     [2, 4, 5/2],
#     [-3/4, 2, 0.25],
#     [0.25, 0.5, 2]
# ])
d_trans = D.T
d_inv = np.linalg.inv(D)
print(f"d_trans: {d_trans}")

print("\n(d_inv)_transpose equals (d_trans)_inv")
print(f"\n{d_inv.T} = \n{np.linalg.inv(d_trans)}")

d_trans: [[ 2.   -0.75  0.25]
 [ 4.    2.    0.5 ]
 [ 2.5   0.25  2.  ]]

(d_inv)_transpose equals (d_trans)_inv

[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]] = 
[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 8: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [53]:
# Write your solutions here

# a)
# 2x + 3y = -1
# x + y = 0
A = np.array([
    [2, 3],
    [1, 1],
])
b = np.array([-1,0])
a_sol = np.linalg.solve(A, b)
print(f"determinat of A: {np.linalg.det(A)}")
print(f"solution to a: [x,y] = {a_sol}")

# b)
# 1x+0y = 5
# 0x + 1y = 7
A = np.array([
    [1, 0],
    [0, 1],
])
b = np.array([5,7])
b_sol = np.linalg.solve(A, b)
print(f"determinat of A: {np.linalg.det(A)}")
print(f"solution to b: [x,y] = {b_sol}")

# c)
# 0x+y = -1
# -2x + -3y = 2
A = np.array([
    [0, 1],
    [-2, -3],
])
b = np.array([-1,2])
c_sol = np.linalg.solve(A, b)
print(f"determinat of A: {np.linalg.det(A)}")
print(f"solution to c: [x,y] = {c_sol}")


# d)
# x + -3y + 3z = 0.5
# x + -5y + 3z = 0.5
# 6z + -6y + 4x = 1
A = np.array([
    [1, -3, 3],
    [1, -5, 3],
    [4, -6, 6],
])
b = np.array([0.5,0.5,1])
d_sol = np.linalg.solve(A, b)
print(f"determinat of A: {np.linalg.det(A)}")
print(f"solution to d: [x,y] = {d_sol}")


# e)
# 2x + 3y + 4z = 2
# x + y + 4z = -2
# 2x + 5y + 4z = 3
A = np.array([
    [2, 3, 4],
    [1, 1, 4],
    [2, 5, 4],
])
b = np.array([2,-2,3])
d_sol = np.linalg.solve(A, b)
print(f"determinat of A: {np.linalg.det(A)}")
print(f"solution to e: [x,y] = {d_sol}")

# f)
# x + y + z = 2
# 2x + 2y + 2z = -2
# 3x + 3y + 3z = 3
A = np.array([
    [1, 1, 1],
    [2, 3, 3],
    [3, 3, 3],
])
b = np.array([2,-2,3])
print(f"determinat of A: {np.linalg.det(A)}")
print("no solution because the determinant is 0")
# d_sol = np.linalg.solve(A, b)
# print(f"solution to f: [x,y] = {d_sol}")


determinat of A: -1.0
solution to a: [x,y] = [ 1. -1.]
determinat of A: 1.0
solution to b: [x,y] = [5. 7.]
determinat of A: 2.0
solution to c: [x,y] = [ 0.5 -1. ]
determinat of A: 12.000000000000005
solution to d: [x,y] = [ 7.93016446e-18 -3.96508223e-18  1.66666667e-01]
determinat of A: -7.999999999999998
solution to e: [x,y] = [ 3.     0.5   -1.375]
determinat of A: 0.0
no solution because the determinant is 0


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 9: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [60]:
def matmul(a, b):
    res = []
    for i in range(len(b)):
        for j in range(len(b)):
            res.append(np.dot(a[i], column(b,j)))

    return np.reshape(res, (len(a), len(b[0])))




def column(matrix, i):
    return [row[i] for row in matrix]


ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]
print(f"using np functions: \n{np.matmul(ma, mb)}")
print(f"using homemade function: \n{matmul(ma, mb)}")

using np functions: 
[[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]
using homemade function: 
[[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]


<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 10: Extra exercises</span>
        <span class="has-text-right">
          <i class="bi bi-lightbulb-fill"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

---
