In [0]:
import requests
from IPython.core.display import HTML
HTML(f"""
<style>
@import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
</style>
""")

# Linear Algebra
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 10: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Define matrices to be used in the tasks:
a_A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

## Matrix Operations
<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [6]:
# Write your solution here
res = a_A - B

print("A - B: \n", res)

A - B 
 [[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.



</div></article>



In [10]:
# Write your solution here
ac = a_A @ C
ca = C @ a_A

print("a @ c = \n", ac)
print("c @ a = \n", ca)

# The results are different, because when calculating matrix multiplication, 
# the order matters, since we're multiplying columns with rows

a * c = 
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
c * a = 
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication - Hadamard product</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.



</div></article>



In [13]:
# Write your solution here
ac = a_A * C

print("a * c: \n", ac)

# The * operator produces elementwise multiplication (Hadamard Product), while the @ operator performs matrix multiplication ()

a * c: 
 [[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 4: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [32]:
# Write your solution here
a_inverse = np.linalg.inv(a_A)
c_inverse = np.linalg.inv(C)

print("Inverse of a: \n", a_inverse)
print("A: \n", a_A)

print("Inverse of c: \n", c_inverse)

res_a = np.round(a_A@a_inverse)
res_c = C@c_inverse

print("AA^-1 (using np.round): \n",res_a)
print("CC^-1: \n", res_c)



# When we use the @ operator, the result is a matrix with floating points, which is not very precise to make calculations on,
# because it has (infinite) many decimals, and at some point when doing calculations on these, we risk getting a float overload
# If we use the np.round operator on the result, we get the correct identity matrix, see res_a vs. res_c

# To read more about floating points, see here https://docs.python.org/3/tutorial/floatingpoint.html



Inverse of a: 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
A: 
 [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
Inverse of c: 
 [[   -72.           -225.            525.             42.        ]
 [  1260.           3675.          -8820.00000001   -630.        ]
 [ -3696.         -10710.00000001  25830.00000002   1764.        ]
 [  2700.           7830.00000001 -18900.00000001  -1260.        ]]
AA^-1: 
 [[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [ 0. -0.  1. -0.]
 [-0.  0. -0.  1.]]
CC^-1: 
 [[ 1.00000000e+00  2.27373675e-13  0.00000000e+00  5.68434189e-14]
 [ 2.99760217e-14  1.00000000e+00 -2.09832152e-13  2.58015831e-14]
 [-6.71808288e-14 -1.11454056e-13  1.00000000e+00  5.19831092e-14]
 [-1.03374099e-14  2.23278186e-15  1.67100901e-13  1.00000000e+00]]


## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 5: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [41]:
# Write your solution here

d_inverse = np.linalg.inv(D)
e_inverse = np.linalg.inv(E)

de_inverse_1 = d_inverse@e_inverse

print("D^-1E^-1: \n",de_inverse_1)

ed = E@D
de = D@E
ed_inverse_1 = np.linalg.inv(ed)
de_inverse_2 = np.linalg.inv(de)

print("(ED)^-1: \n", ed_inverse_1)

print("(DE)^1: \n", de_inverse_2)

D^-1E^-1: 
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
(ED)^-1: 
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
(DE)^1: 
 [[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 6: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [47]:
# Write your solution here
a_det = np.linalg.det(a_A)
b_det = np.linalg.det(B)
c_det = np.linalg.det(C)

print(a_det, b_det, c_det)

# 6.2:
# A and C have an inverse. B doesn't have an inverse, since its determinant = 0

a_inv = np.linalg.inv(a_A)
# b_inv = np.linalg.inv(B)
c_inv = np.linalg.inv(C)

print(a_inv)
# print(b_inv)
print(c_inv)

# 6.3
# It is not possible to calculate the inverse of B, since the denominator = 0, and we're performing division by 0 which is not allowed.

1.6534391534390412e-07 0.0 1.0498026371034301e-07
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[   -72.           -225.            525.             42.        ]
 [  1260.           3675.          -8820.00000001   -630.        ]
 [ -3696.         -10710.00000001  25830.00000002   1764.        ]
 [  2700.           7830.00000001 -18900.00000001  -1260.        ]]


<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 7: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [48]:
# Write your solution here
d_inverse = np.linalg.inv(D)
d_transpose = D.T

d_inverse_transpose = d_inverse.T
d_transpose_inverse = np.linalg.inv(d_transpose)

print("(D^-1)^T: \n", d_inverse_transpose)
print("(D^T)^-1: \n", d_transpose_inverse)

(D^-1)^T: 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
(D^T)^-1: 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 8: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [85]:
# Write your solutions here


# a)
# 2x + 3y = -1
# x + y = 0

a_A = np.array([[2, 3],
     [1, 1]])

b_b = np.array([-1, 0])

a_res = np.linalg.solve(a_A, b_b)
print("\na)")
print("[x, y] result: ", a_res)
print("Determinant: ", np.linalg.det(a_A))

# b)
# 1x + 0y = 5
# 0x + 1y = 7

b_A = np.array([[1, 0],
       [0, 1]])

b_b = np.array([5, 7])

b_res = np.linalg.solve(b_A, b_b)
print("\nb)")
print("[x, y] result: ", b_res)
print("Determinant: ", np.linalg.det(b_A))

# c)
# 0x + y = -1
# -2x + -3y = 2

c_A = np.array([[0, 1],
       [-2, -3]])

c_b = np.array([-1, 2])

c_res = np.linalg.solve(c_A, c_b)
print("\nc)")
print("[x, y] result:", c_res)
print("Determinant: ", np.linalg.det(c_A))

# d)
# x + -3y + 3z = 0.5
# x - 5y + 3z = 0.5
# 6z + -6y + 4x = 1

d_A = np.array([[1, -3, 3],
                [1, -5, 3],
                [4, -6, 6]])

d_b = np.array([0.5, 0.5, 1])

d_res = np.linalg.solve(d_A, d_b)
print("\nd)")
print("[x, y, z] result:", d_res)
print("Determinant: ", np.linalg.det(d_A))

# e)
# 2x + 3y + 4z = 2
# x + 4z + y = -2
# 4z + 5y + 2x = 3

e_A = np.array([[2, 3, 4],
                [1, 1, 4],
                [2, 5, 4]])

e_b = np.array([2, -2, 3])

e_res = np.linalg.solve(e_A, e_b)
print("\ne)")
print("[x, y, z] result:", e_res)
print("Determinant: ", np.linalg.det(e_A))

# f)
# x + y + z = 2
# 2x + 2z + 2y = -2
# 3z + 3y + 3x = 3

f_A = np.array([[1, 1, 1],
                [2, 2, 2],
                [3, 3, 3]])

f_b = np.array([2, -2, 3])

# f_res = np.linalg.solve(f_A, f_b)
print("\nf)")
print("[x, y, z] result:", "no result")
print("Determinant: ", np.linalg.det(f_A))




a)
[x, y] result:  [ 1. -1.]
Determinant:  -1.0

b)
[x, y] result:  [5. 7.]
Determinant:  1.0

c)
[x, y] result: [ 0.5 -1. ]
Determinant:  2.0

d)
[x, y, z] result: [ 0.         -0.          0.16666667]
Determinant:  12.000000000000005

e)
[x, y, z] result: [ 3.     0.5   -1.375]
Determinant:  -7.999999999999998

f)
[x, y, z] result: no result
Determinant:  0.0


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 9: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [0]:
def matmul(a, b):
    # Implement this function
    ...
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)

<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 10: Extra exercises</span>
        <span class="has-text-right">
          <i class="bi bi-lightbulb-fill"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

---
