## Agenda

#### Exercise Description

This exercise was about learning how to reason about, and apply matrix operations like 
- Elementwise addition and multiplication, 
- Matrix multiplication
- Transposition
- Inverses
- Determinants

Some of these: Fundamental to machine learning
    - Matrix multiplication: Solving systems of equations
    - Matrix inverse / transposition: PCA

## a)

- Define/describe a matrix
- Addition (elementwise)
- Multiplication (elementwise - Hadamard product)
- Matrix multiplication
    - A series of inner products (dot products)
    - Not commutative unless symmetrical
- Transposition (rows become columns)
- Linear transformations
    - Essentially a function (vector -> T(vector))
    - All lines remain straight (preserve parallelism)
    - Origin remains fixed
    - Draw basis vectors $i = \begin{bmatrix} 1 \\ 0\end{bmatrix}$ and $j = \begin{bmatrix} 0 \\ 1\end{bmatrix}$
    - Apply rotation: Now $i = \begin{bmatrix} 0 \\ 1\end{bmatrix}$ and $j = \begin{bmatrix} -1 \\ 0\end{bmatrix}$
    - Put those in a matrix A, that transforms vectors from before rotation to after
- Inverse
    - Transformation in reverse
        -   If $A = \begin{bmatrix} 0 \ -1 \\ 1 \ 0 \end{bmatrix}$, then $A^{-1} = \begin{bmatrix} 0 \ 1 \\ -1 \ 0 \end{bmatrix}$
    - $A^{-1}A = \begin{bmatrix} 1 \ 0 \\ 0 \ 1\end{bmatrix}$
        - Identity matrix
    - Role in solving linear systems of equations
    - Role in translating between data space and latent space
- Determinant
    - Use i and j from before to describe area
    - d = 0: no inverse
- Orthogonality
    - dot product = 0
    - linearly independent


## b)

- System of linear equations, draw examples
    - 2x + 5y + 3z = -3
    - 4x + 0y + 8z = 0
    - 1x + 3y + 0z = 2
    - Then rewrite as matrix / vectors
- Coefficients / design matrix
- Model parameters
- Output / labels
- Explain A as a transformation of x
- Solve for x by reversing transformation


# Linear Algebra
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
            <li>
            <a href="#inverses">Task 4: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 6: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 7: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 8: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 9: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 10: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)

## Matrix Operations
<article class="message task"><a class="anchor" id="diff"></a>
    <div class="message-header">
        <span>Task 1: Elementwise difference</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $A-B$ in the code cell below.



</div></article>



In [8]:
# Write your solution here
answer = A - B
print('A: \n', A, '\n')
print('B: \n', B, '\n')

print(answer)

A: 
 [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]] 

B: 
 [[-16  15 -14  13]
 [-12  11 -10   9]
 [ -8   7  -6   5]
 [ -4   3  -2   1]] 

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]


<article class="message task"><a class="anchor" id="mul_prop"></a>
    <div class="message-header">
        <span>Task 2: Multiplication properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).
2. Explain why the results are different.



</div></article>



In [35]:
# 2.1
# Write your solution here

dotAC = np.dot(A, C)
print(f"np.dot(A, C) = ")
print(dotAC)
atAC = np.dot(C, A)
print(f"np.dot(C, A) = ")
print(atAC)

np.dot(A, C) = 
[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
np.dot(C, A) = 
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


In [21]:
# 2.2
# Matrix multiplication is not commutative. For A x C and C x A to be identical, both matrices would have to be symmetrical, meaning A = A^T and C = C^T. The fact that 
# the results are only slightly different indicates that they are 'almost' symmetrical.

<article class="message task"><a class="anchor" id="elem_mul"></a>
    <div class="message-header">
        <span>Task 3: Elementwise multiplication - Hadamard product</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.



</div></article>



In [19]:
# Write your solution here

element_wise_mult = A * C
print(element_wise_mult)

# * is the operator for elementwise multiplication, which simply multiplies each entry in a matrix with the corresponding one in another.
# @ is the operator for matrix multiplication which uses inner product to calculate each new entry.

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]
[[-1 12]
 [-6 32]]


<article class="message task"><a class="anchor" id="inverses"></a>
    <div class="message-header">
        <span>Task 4: Inverses</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">

  The question relates to the limitations of floating point numbers.


  </div>
</article>


</div></article>



In [29]:
# Write your solution here
inverseA = np.linalg.inv(A)
prodAinvA = np.round(A @ inverseA, 2)
inverseC = np.linalg.inv(C)
prodCinvC = np.round(C @ inverseC, 2)

print('A \n', A)
print('inv A \n', inverseA)
print('prodAinvA \n', prodAinvA)
print()
print("C")
print('C \n', C)
print('inv C \n', inverseC)
print('prodCinvC \n', prodCinvC)

A 
 [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
inv A 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
prodAinvA 
 [[ 1.  0.  0.  0.]
 [-0.  1. -0. -0.]
 [ 0. -0.  1. -0.]
 [-0.  0. -0.  1.]]

C
C 
 [[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.2        0.14285714 0.11111111]
 [0.25       0.14285714 0.125      0.11111111]]
inv C 
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]
prodCinvC 
 [[ 1.  0.  0.  0.]
 [-0.  1.  0. -0.]
 [-0. -0.  1. -0.]
 [-0.  0. -0.  1.]]


## Properties
<article class="message task"><a class="anchor" id="inverse_prop"></a>
    <div class="message-header">
        <span>Task 5: Inverse properties</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$



</div></article>



In [36]:
# Write your solution here
inverseD = np.linalg.inv(D)
inverseE = np.linalg.inv(E)
print("InvD times InvE = ")
print(inverseD @ inverseE)
print()

E_mult_D = np.linalg.inv(E @ D)
print('Inv ED \n', E_mult_D, '\n')

D_mult_E = np.linalg.inv(D @ E)
print('Inv DE \n', D_mult_E)


InvD times InvE = 
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]

Inv ED 
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]] 

Inv DE 
 [[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]


<article class="message task"><a class="anchor" id="determinant"></a>
    <div class="message-header">
        <span>Task 6: The determinant</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).



</div></article>



In [44]:
# Write your solution here
# 1:
detA = np.round(np.linalg.det(A), 10)
detB = np.round(np.linalg.det(B), 10)
detC = np.round(np.linalg.det(C), 10)
print(f"detA = {detA}, detB = {detB}, detC = {detC}")
print()

# 2:
# A and C are invertible, since d !=
# B has a determinant of 0, meaning it does not have an inverse.

# 3:
invA = np.linalg.inv(A)
invB = np.linalg.inv(B)
invC = np.linalg.inv(C)

print('InvA: \n', invA, '\n')
print('InvB: \n', invB, '\n')
print('InvC: \n', invC, '\n')

# Theoretically, InvB should fail. However floating point arithmetics introduce inaccuracies
# which in turn makes numpy attempt the inversion regardless of the expected failure,
# because it reads the determinant as nearly 0 instead of exactly 0. This results in
# a false result with very large numbers, instead of a failure.

print('Condition number for B: ', np.linalg.cond(B))
# A high condition number indicates that B is ill-conditioned.
# Basically it means, we should treat it as though d = 0, and no inversion is possible.

detA = 1.653e-07, detB = 0.0, detC = 1.05e-07

InvA: 
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]] 

InvB: 
 [[-3.00239975e+16  4.80383960e+16 -6.00479950e+15 -1.20095990e+16]
 [-4.80383960e+16  7.20575940e+16 -0.00000000e+00 -2.40191980e+16]
 [-6.00479950e+15  0.00000000e+00  1.80143985e+16 -1.20095990e+16]
 [ 1.20095990e+16 -2.40191980e+16  1.20095990e+16 -0.00000000e+00]] 

InvC: 
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]] 

Condition number for B:  3.0289009048311014e+17


<article class="message task"><a class="anchor" id="transpose"></a>
    <div class="message-header">
        <span>Task 7: Transpose</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.

<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.

  
  </div>
</article>



</div></article>



In [46]:
# Write your solution here
print('Transposed(Inverse of D): \n', np.linalg.inv(D).T)
print()
print('Inverse(Transposed(D)) \n', np.linalg.inv(D.T))

Transposed(Inverse of D): 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]

Inverse(Transposed(D)) 
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$
<article class="message task"><a class="anchor" id="eqsys"></a>
    <div class="message-header">
        <span>Task 8: Solving linear equation systems</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


</div></article>



In [73]:
def solve(a, b, ass):
  print(f"{ass} = {np.linalg.solve(a, b)}, determinant = {np.round(np.linalg.det(a), 10)}")

# Write your solutions here
aA = np.array([[2, 3], [1, 1]])
aB = np.array([-1, 0])
solve(aA, aB, "a")

bA = np.array([[1, 0], [0, 1]])
bB = np.array([5, 7])
solve(bA, bB, "b")

cA = np.array([[0, 1], [-2, -3]])
cB = np.array([-1, 2])
solve(cA, cB, "c")

dA = np.array([[1, -3, 3], [1, -5, 3], [4, -6, 6]])
dB = np.array([0.5, 0.5, 1])
solve(dA, dB, "d")

eA = np.array([[2, 3, 4], [1, 1, 4], [2, 5, 4]])
eB = np.array([2, -2, 3])
solve(eA, eB, "e")

fA = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
fB = np.array([2, -2, 3])
solve(fA, fB, "f")


a = [ 1. -1.], determinant = -1.0
b = [5. 7.], determinant = 1.0
c = [ 0.5 -1. ], determinant = 2.0
d = [ 7.93016446e-18 -3.96508223e-18  1.66666667e-01], determinant = 12.0
e = [ 3.     0.5   -1.375], determinant = -8.0
f = [-1.80143985e+16 -3.60287970e+16  5.40431955e+16], determinant = -0.0


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.
<article class="message task"><a class="anchor" id="matmul"></a>
    <div class="message-header">
        <span>Task 9: Implementing matrix multiplication</span>
        <span class="has-text-right">
          <i class="bi bi-code"></i><i class="bi bi-stoplights medium"></i>
        </span>
    </div>
<div class="message-body">


Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.
<article class="message is-warning">
  <div class="message-header">Hint</div>
  <div class="message-body">
  
  It might be helpful to calculate the correct result by hand first, to make debugging easier.

  
  </div>
</article>



</div></article>



In [52]:
# This is just homebrew of np.dot
def matmul(a, b):
    # Get the dimensions of input matrices
    n, d1 = len(a), len(a[0])  # Rows and columns of matrix `a`, N x D
    d2, k = len(b), len(b[0])  # Rows and columns of matrix `b`, D x K
    
    # Ensure the inner dimensions match (a's columns = b's rows)
    if d1 != d2:
        raise ValueError("Matrix dimensions do not match for multiplication!")
    
    # Initialise result matrix with zeros of shape  N x K
    result = [[0 for _ in range(k)] for _ in range(n)]
    
    # Perform the matrix multiplication
    for i in range(n):            # Loop over rows of `a`
        for j in range(k):        # Loop over columns of `b`
            for d in range(d1):   # Loop over the shared dimension
                result[i][j] += a[i][d] * b[d][j]  # Sum the product of elements
    
    return result

# Pretty-print function
def print_matrix(matrix):
    for row in matrix:
        print(row)

# Test case
ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

print_matrix(matmul(ma, mb))
print('\n Numpy dot result = \n', np.dot(ma, mb))

[33, 6, 26]
[78, 21, 77]
[123, 36, 128]

 Numpy dot result = 
 [[ 33   6  26]
 [ 78  21  77]
 [123  36 128]]


<article class="message task"><a class="anchor" id="extra"></a>
    <div class="message-header">
        <span>Task 10: Extra exercises</span>
        <span class="has-text-right">
          <i class="bi bi-lightbulb-fill"></i><i class="bi bi-stoplights easy"></i>
        </span>
    </div>
<div class="message-body">


Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)




</div></article>

---
